name : CI

on: 
  push:
  pull_request:

jobs: 
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 'Init repository'
        uses: actions/checkout@v3
      - name: 'Setup NodeJs'
        uses: actions/setup-node@v2
        with:
          tools: npm
      - name: "Install dependencies"
        run: npm install
      - name: "Run Test"
        run: npm run test
      - name: 'Run linter'
        run: npm run lint
